language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: chefhook
  api_key:
    secure: dO1jfJIrjwGrFNinvvF0BTyc5pOhS7MhoUPQMZOHAtQtyyXmefoG3oAsNy6iefxSpIUndAS8l/FzWvTz94w6LyQggzqge7agrQ1VkxBrHeTiOb0+z0pTyNeNXUE2a52CkQnqtHKeMczCgBqj1nFfXsfgLq+DvxvWUq4xCkAUV+SPN0E0Gwc9meetlnDRtCPsdFraFzvc6FI0vslUbjkhLhCpcqk+qh6f1QnpttQtvv2ZO9YLsRMZwjEZo3lqwykB7WSZWYKHROxF0I42pgHKCJ7afLoYyWVhcQGy56FWOV+51WgCxZKZvCRLjrx3C6nEyXRMCFKNp4RTsNGtck3JpJ/SDfs+DfMMqUJanUGcUzAVea6k1jWsLSuIQJq+CL4wA8Aa81Tzq4GCrWsnyjWiygm9N7oFr38F6CiOc7V0SGKVPkCgnbleTs/UDd5cK4AYzZiZmhmVQBDI/GW+80BunkUS3hWXiJ9YJ7+llEPu7aBSa1LCY07kJTK/GrUXqtVvIhMbKej1Zgb1woA8PuqnVUG3eVevWSM7Qf0lgwx/E1CaXH3tt9BTx7LPd3fO37Qvx6XLZFdwdz8au8jCL9n3tU+XWVddetpx8NElC3zcbkjiboqM7I09ej5kci1I9v24gNK7Q0ptLrlRQPlxHqAh8n39PcFv1M7eOQToAP16gp0=
