language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: chefhook
  api_key:
    secure: sQih5W+V2orFW9/oTvUDNroq2gyEIwWWOlSDvozJIksRBJl4tTRq0lkLvx4/wsBBtUMEGLNg5FK+qTY3lVCIb7XMewx4WVoO2kQ/p8z/I05kwp0ZvZCWNWRO6C4ea5QauFK3i1Xehd+64sC/UTGJyc8xPKPvsqp0bK2Hb1ZsSZmtJKN6BYSq+7XuRrPreJPKEYZ/cmYJMuOi6wmEdSzoc/jD4RgASZ7ZQxZ+ri9fT3CeIKMQA8bhYbXvCFxays3kX40RJjfQZpChuOpuHlFYbLO5rTnrAZGVkr+cYae6wIaj2MO0s1OD+F3QwT+mTaFOnezMcVAqrZxHdzikPSBSjhfJ4phFztViO0A+V1+BJJwokPyxWZj3Z9BGYl4AKwIfNCswbx0JirhijtTTysPuJBJLHw25DbuIa/a5DVkHyjykLuXZD+5CY4DLnIwf9rsprrgluXI0/dS4NEKUdlYZviTn+ELkuNd+D+Hd36CVP/jsWkdXms81KJWSKrK01wAwUL6hNbwbPqby82OGkOxdizwFGhcaa2dzCyxcBPahqHqXbsW0xgEg1SZjevV48KvPYtzBJSZ6YVwcocFTFN/b0T4v1oLFL9fba9Y4bruKghh+QC/s/TWWiHLzz6/ARaVx5kKOcFLAMCNOu3xnbyL7UMWuaBObW1F8RW7XtY+lo80=
