language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: chefhook
  api_key:
    secure: MCscP8jPrm/IgWbqpRmpxGtkLE3G7xGdql3ADd24kV6h537l4rmn1sMMpZbM91/I25OoQ8A38fn0nCS5RCg4txd5Yjv8eQKK4BF/U3yMSg64XoNW/LDFIt0L2dcZ7IboNC1O2J8pZwwqiN8DXIApqcpOtHD7VNTM3gyR1APQgrh2aRf/HzvzkhuCcD3C8Ypf59MT6U27U21wx/bu8Xb8IU9qFdz0vcDL8olSMjL7QLTJGtJgpw0BvFmSrXzz/3G1WigFyFOUUvGt8ulHpKYIpWAu5wCqb2fzLiurqEwtYVGyCcIiogcnVcdy/gukNfdv1sT6nUM4hLpC/gy2fydXdDXp/tJzd+XdhKJwhxC5NteKM5VJfJtUgv9NHe2k3GDG1YSFub/bKeZJWMSDcE2weLPBWeGtJcZ8MEQgiaLqeEoQIDu78wPfG0gvJYc/w9/prgGw1vYxvXi4a3O8q0goUd9fh8sFRl0Hef7Iei39YpgK2HLCDhSPVWDKIMKnSwAItVcuKSFu8UIO/2HOkq5uOdP8OV/LAs7aZ831uKMql9SwN3YBXWVaEMCoHJ5BslbVZB6TwgPt9/pVgk2DqLfz5ExfukAd4qY5Ep9cIpssrd6C55YGCCjgvEIXJnAM7CQWv6GLI/RbalSlXNehHOrzlEHzHyZw48gPIhDvLSBFbNU=
