language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: chefhook
  api_key:
    secure: J7UuKrpblK/DwEUNX5i751BpdbLFdZ/AwQHER8HtIwaGA230huIdisyDgTnVV7BqESAst9BPZ2Ye483V+AcYKZsslogdMDTaILkxWX6zV5vjmM8sVeoqInsG2JiPBzLF0Qjm+h+2ZBozF1jTotfaRPIaWlBPX1Eu8DCCyv8z6BEIzQcI2chaVgfuHeAYOheBEYixE8NZEzKfhJ9CZq19H6jxKPXqiXL7fmgGuEhBCPZhwbydODIOPEa0W9uTIvXXR1CyPPjsSJlJAVqc2/W5pmUlB3fNgkwunM5s1O3yHsl+t42+PND5FU4hkNEYlZQyV4ROA0TTeWQ9ZE4OuZLptsx1hisIAPSGkqFktlB7EjV4+oloOakiCWtiiCeYYDCR2fx4GYD1HDGVdlUjO56c1V4hSILoFFApyayL6Dv7ue6rOiJVbR0xWV41RjKedGd5vYbphr5LnS5O9GaJzURzQW6ZpPYzjMB80fI4c66Tk4qgAHOKqXOd14lXu7GKozvTGKMpVwFMJpboF61gUlGGZZIEUKkRJHUrTvw4qPFNoE3Adjk9JaRLooAkyun8Tj1Tz351J7HXVH6W31mKGBIIJb/863UjnM6zEXssdDs3KcnqpX1mRuoHVp6sTNhptcJlJk6y8k9BcV+AcgpgIE98RdYYor5Moj0ASHzDs3VAqG8=
